### ISSUE TITLE
jx project butchers Chart.yaml dependencies

### ISSUE THREAD

**Issue by joshuasimon-taulia** [jenkins-x-plugins/jx-project#437]
[this loop](https://github.com/jenkins-x-plugins/jx-project/blob/655f3722f4ee8fc165e3777ecaa512786bd057aa/pkg/cmd/importcmd/import.go#L1057-L1061) performs replacements without loading/appending to yaml objects.

To recreate:
1. create custom pack in custom catalog
2. add dependencies dict to Chart.yaml and push to git
3. jx project spring --dry-run or jx project import
4. `jx project` renders invalid Chart.yaml

pack Chart.yaml:
```yaml
apiVersion: v2
dependencies:
- alias: mysql
  condition: mysql.enabled
  name: mysql-cluster
  repository: https://presslabs.github.io/charts
  version: 0.3.0
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
name: REPLACE_ME_APP_NAME
version: 0.1.0-SNAPSHOT
```

rendered/charts/rendered/Charts.yaml:
```yaml
apiVersion: v2
dependencies:
- alias: mysql
  condition: mysql.enabled
name: asdf
  repository: https://presslabs.github.io/charts
  version: 0.3.0
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
name: asdf
version: 0.1.0-SNAPSHOT
```

the above method should be yaml-aware or at least use a replacement pattern that's anchored to a line beginning.
